#define COMMA                            1
#define ASSIGN                           2
#define ADDEQ                            3
#define MINUSEQ                          4
#define BIOR                             5
#define BIAND                            6
#define OR                               7
#define XOR                              8
#define AND                              9
#define EQ                              10
#define NOTEQ                           11
#define LSS                             12
#define LSSEQ                           13
#define GRT                             14
#define GRTEQ                           15
#define ADD                             16
#define MINUS                           17
#define DIV                             18
#define MOD                             19
#define MULTI                           20
#define BIADD                           21
#define BIMINUS                         22
#define NOT                             23
#define BITNOT                          24
#define LOWELSE                         25
#define ELSE                            26
#define INT                             27
#define FLOAT                           28
#define CHAR                            29
#define LMB                             30
#define INUM                            31
#define RMB                             32
#define ID                              33
#define SEMICOLON                       34
#define LLB                             35
#define RLB                             36
#define LGB                             37
#define RGB                             38
#define RETURN                          39
#define IF                              40
#define WHILE                           41
#define FOR                             42
#define FNUM                            43
#define CNUM                            44
